// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvabuwroqlgnbgnryazd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2YWJ1d3JvcWxnbmJnbnJ5YXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDE2NzYsImV4cCI6MjA2OTkxNzY3Nn0.RALlaxbd_DWbtqFShTL8hfZ3VYlh1I7318htQX8a4Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});